name: pnpm
description: 'Setup node & pnpm'

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 9
        run_install: |
          - recursive: true
            args: [--frozen-lockfile, --strict-peer-dependencies]
    - uses: actions/setup-node@v3
      with:
        node-version: 22
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'
