name: Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # path to built static site directory
  outputDir: out

jobs:
  preview:
    name: Preview
    if: (github.ref != 'refs/heads/main')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm build
      - name: Add to web3.storage
        uses: storacha/add-to-web3@v3
        id: ipfs
        with:
          path_to_add: ${{ env.outputDir }}
          secret_key: ${{ secrets.W3_PRINCIPAL }}
          proof: ${{ secrets.W3_PROOF }}
      - name: Deploy preview build to Cloudflare Pages
        uses: mathiasvr/command-output@v1.1.0
        id: cloudflare
        with:
          run: npx wrangler pages deploy --project-name storacha-docs-website-staging --branch "$GITHUB_REF_NAME" --commit-hash "$GITHUB_SHA" ${{ env.outputDir }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      - name: Find Cloudflare Pages preview URL
        uses: mathiasvr/command-output@v1.1.0
        id: cloudflare_url
        with:
          run: egrep -o 'https?://[^ ]+' <(echo "${{ steps.cloudflare.outputs.stdout }}")
      - name: Find Current Pull Request
        uses: jwalton/gh-find-current-pr@v1.3.0
        id: finder
      - name: Update Preview URLs PR Comment
        uses: marocchino/sticky-pull-request-comment@v2.2.0
        with:
          number: ${{ steps.finder.outputs.pr }}
          message: |
            ### Website preview 🔗✨
            - 🙂 https://${{ steps.ipfs.outputs.cid }}.ipfs.storacha.link
            - ⛅️ ${{ steps.cloudflare_url.outputs.stdout }}

            [build log](/${{ github.repository }}/actions/runs/${{ github.run_id }})
      - name: Add Preview URLs as Job Summary
        run: |
          echo "
          ### Website preview 🔗✨
          - 🙂 https://${{ steps.ipfs.outputs.cid }}.ipfs.storacha.link
          - ⛅️ ${{ steps.cloudflare_url.outputs.stdout }}
          " >> $GITHUB_STEP_SUMMARY

  release:
    name: Release
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://docs.storacha.network
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm build
      - name: Add to web3.storage
        uses: storacha/add-to-web3@v3
        id: ipfs
        with:
          path_to_add: ${{ env.outputDir }}
          secret_key: ${{ secrets.W3_PRINCIPAL }}
          proof: ${{ secrets.W3_PROOF }}
      - name: Deploy preview build to Cloudflare Pages
        uses: mathiasvr/command-output@v1.1.0
        id: cloudflare
        with:
          run: npx wrangler pages deploy --project-name storacha-docs-website --branch "main" --commit-hash "$GITHUB_SHA" ${{ env.outputDir }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      - name: Add Preview URLs as Job Summary
        run: |
          echo "
          ### Deployed
          ⁂ https://docs.storacha.network

          ### Snapshot urls 🔗✨
            - 🙂 https://${{ steps.ipfs.outputs.cid }}.ipfs.storacha.link
            - ⛅️ ${{ steps.cloudflare_url.outputs.stdout }}
          " >> $GITHUB_STEP_SUMMARY
